name: Update Timestamp

on:
  push:
    branches: [main]

  schedule:
    - cron: '0 */1 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Debug Information
        run: echo "::debug::Triggered by ref = ${{github.ref}}"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Update Timestamp File
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time" > TIMESTAMP.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "maladarsih@gmail.com"
          git config user.name "Winnode"

      - name: Prepare Commit
        run: |
          commit_messages=(
            "Update: â°"
            "Refresh: ğŸ”„"
            "Renew: ğŸŒŸ"
            "Revise: ğŸ“"
            "Amend: ğŸ› "
            "Adjust: ğŸ”§"
            "Change: ğŸ“ˆ"
            "Modify: ğŸ–Š"
            "Transform: ğŸŒ€"
            "Revamp: ğŸŒˆ"
            "Enhance: ğŸ’¡"
            "Optimize: âš™ï¸"
            "Fix: ğŸ›"
            "Feature: âœ¨"
            "Implement: ğŸš€"
            "Upgrade: ğŸš€"
            "Refactor: ğŸ› "
            "Debug: ğŸ"
            "Document: ğŸ“š"
            "Test: ğŸ§ª"
            "Review: ğŸ‘€"
            "Release: ğŸš€"
            "Merge: ğŸ‘¥"
            "Initialize: ğŸš€"
            "Resolve: ğŸ”§"
            "Revert: âª"
            "Synchronize: ğŸ”„"
            "Add: â•"
            "Remove: â–"
            "Rename: ğŸ”„"
            "Move: â†”ï¸"
            "Deploy: ğŸš€"
            "Rollback: âª"
            "Hotfix: ğŸ”¥"
            "Chore: ğŸ§¹"
            "Style: ğŸ¨"
            "Lint: ğŸ§¹"
          )
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}

          if [[ $(git status --porcelain) ]]; then
            git add TIMESTAMP.txt
            git commit -m "$random_msg - $current_time"
          else
            echo "No changes to commit."
          fi

      - name: Fetch latest changes from origin
        run: git fetch origin main

      - name: Merge changes from origin/main
        run: git merge origin/main --no-edit || echo "Conflict"

      - name: Resolve merge conflicts
        if: ${{ success() }}
        run: |
          git checkout --ours TIMESTAMP.txt
          git add TIMESTAMP.txt
          git commit -m "Resolve merge conflict by keeping local changes" || echo "No conflict to resolve"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: '.'
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
